---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-0235
    - profile-0235
    - user-0235
    - webserver-0235

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"